server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: myserver
      port: 8500
      discovery:
        prefer-ip-address: true
        hostname: 192.168.2.128
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}
